name: 'OpenText Functional Testing GitHub Action'
description: 'Enable your GitHub repository to trigger FT test runs.'
inputs:
  runType:
    description: 'Type of run: filesystem | filesystem-parallel | alm | alm-lab'
    required: false
    default: "filesystem"
  testPaths:
    description: 'Path to the a tests directory or to a specific test folder (i.e. "path\to\folder" or "path\to\GUITest1"). For multiple individual tests you can use an array of paths: ["path\\to\\GUITest1", "path\\to\\GUITest2", ...]. A path can be either absolute or relative. The relative paths will be computed against the repository root.'
    required: true
  timeout:
    description: 'The number of seconds before the test run times out.'
    required: false
    default: ""
  cancelRunOnFailure:
    description: 'Whether to cancel the test run on first failure'
    required: false
    default: "false"
  resultTestNameOnly:
    description: 'Indicates whether the test results summary file should include only test names for FT tests, rather than full paths. By default the test results summary file includes the full path of the FT test. For example: <testcase name="C:\tests\GUITest1". When this parameter is set to "true", the results show the test name only: <testcase name="GUITest1".'
    required: false
    default: "true"
  resultUnifiedTestClassname:
    description: 'This parameter is relevant only if runType is "filesystem". It does not affect tests stored in ALM. For example, if the test path is: "C:\UFTTests\Level1\Level2\Level3\GUITest1" and this parameter is set to "true", the classname will be "file:///C:/UFTTests/Level1/Level2/Level3" (the absolute path of the closest parent folder). This result is consistent, whether you use an MTB / MTBX file or a folder path (with one or more tests stored at folder and/or subfolders level). If this parameter is set to "false", the classname can be: "All-Tests.Test group" if the properties file provides the full path to the test folder, or "All-Tests.<path to the mtb or mtbx file>" if the properties file provides a mtb / mtbx file path, or "All-Tests.C:\UFTTests\Level1" if the properties file provides a partial path (to the subfolder Level1).'
    required: false
    default: "false"
  labUrl:
    description: 'OpenText Functional Testing Lab Server URL, format: http(s)://{hostname-or-ip}[:{port}]'
    required: false
    default: ""
  labExecToken:
    description: 'OpenText Functional Testing Lab Exec Token'
    required: false
    default: ""
  githubToken:
    description: 'GitHub PAT'
    required: true
  ftlUrl:
    description: 'The URL of OpenText FTToolsLauncher.exe'
    required: false
    default: "https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/download/v25.2.0/FTToolsLauncher_net48.exe"
  logLevel:
    description: 'Sets the log level (1-5): 1-trace, 2-debug, 3-info, 4-warn, 5-error'
    required: false
    default: "3"
runs:
  using: 'node24'
  main: 'dist/index.js'
